language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
