version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_reviewers:
      - 'Nargonath'
    default_assignees:
      - 'Nargonath'
    default_labels:
      - 'dependency'
    target_branch: 'develop'
